title : Nred Yssuts
tagline: Developer and friend of open-source
author :
  name : Nred Yssuts
  email : nredyssuts@gmail.com
  github : nredyssuts
  twitter : nredyssuts
  appdotnet : nredyssuts

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
